### ISSUE TITLE
Feature required- Popup message text from Unity

### ISSUE THREAD

**Issue by Amitkapadi** [Balaso-Software/app-tracking-transparency-for-unity#10]
We wants to do AB test with different message. But right now plugin fetch message from plist. So we cant change message using Remote config. Is it possible to set message from Unity before RequestTrackingAuthorization.

**Comment by manelizzard** [comment]
Hello @Amitkapadi. Apple requires the popup message to be set in Info.plist upon build time. Because of that, we cannot A/B test the popup message, I am sorry.

**Comment by andymads** [comment]
@manelizzard As an addition can I suggest you make the popup message setting be optional - add a checkbox to disable. And do the same with the SKAdNetwork additions, and the framework additions. I prefer to have full control and not have third-party code making modifications to my Xcode project.
