### ISSUE TITLE
Can no longer use simulators

### ISSUE THREAD

**Issue by chebedzic** [Balaso-Software/app-tracking-transparency-for-unity#12]
Hello,

When trying to use simulators on exported builds I get an error:
"Building for iOS Simulator, but the linked library 'libAppTrackingTransparency.a' was build for iOS".

This is pretty important since we are getting crashes on people who have iOS version 11, wanted to check if its due to this plugin, or something else, now I can't since I don't have a device with iOS 11, nor I can use simulators. Would mean a lot if this was added for the next release.

Thanks in advance.

**Comment by gevorgyanmp** [comment]
Hello,

I have that problem too, when trying to run build on iPhone 11(14.0.1) simulator

**Comment by manelizzard** [comment]
Hello! Glad to announce simulator are fully supported since version 2.2.

**Comment by kodkuce** [comment]
Hmm, i am still getting error when i put it in simulator still


![2022-02-07_17-00](https://user-images.githubusercontent.com/24373114/152826173-9b0052f5-485b-41ff-bb75-ec8de2cc4d6b.png)
