### ISSUE TITLE
Feature Request - Localization

### ISSUE THREAD

**Issue by dpodz** [Balaso-Software/app-tracking-transparency-for-unity#14]
Hi there! It would be extremely helpful if you provided a default interface for localizing the popup message description. As is, it's not too hard to implement on our own, but it seems like a feature that should be included with this package.

**Comment by SimoHamalainen** [comment]
For us it would work best if the Popup Message could be set during runtime, because we're using a separate plugin to do all of the localisation for us.

**Comment by andymads** [comment]
It doesn't work that way. The message string (and any localisations) are set via info.plist.

**Comment by dpodz** [comment]
Yep! Localizations are set via info.plist. It'd be nice to have a built-in interface for setting this though, rather than coding it ourselves.

**Comment by agrobost** [comment]
You can look at the code of AppLovin-MAX-Unity-Plugin, they handle the "user tracking usage description" translation for several languages
https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/blob/master/DemoApp/Assets/MaxSdk/Scripts/Editor/MaxPostProcessBuildiOS.cs

**Comment by manelizzard** [comment]
Hello @agrobost @dpodz @andymads @SimoHamalainen:

We have added localization support in the brand new version v2.3: https://assetstore.unity.com/packages/tools/integration/app-tracking-transparency-for-unity-ios-14-idfa-174256

Hope you find it useful and do not hesitate to reach out for any bug/inquiry/suggestion.

Thanks all for your input and feedback.

Best

PS: @andymads I know you implemented your own localization system. If you update, you will see a checkbox to use plugin's localization system or leave it without effect. Just uncheck it.

**Comment by agrobost** [comment]
Nice, thank you very much!
