### ISSUE TITLE
Is it possible to check if the ATT dialogue was actually displayed for the user?

### ISSUE THREAD

**Issue by SimonImpact** [Balaso-Software/app-tracking-transparency-for-unity#15]
Hi,
I noticed that the ATT dialogue is not displayed for example for iOS12 users when calling the RequestTrackingAuthorization function. Same situation if trying to call the function when the user has already given an answer.

Is it possible to check if the dialogue was actually shown or not after calling RequestTrackingAuthorization?

Best Regards
Simon

**Comment by andymads** [comment]
App Tracking Transparency only applies on iOS 14+.

You can call AppTrackingTransparency.TrackingAuthorizationStatus to get the current status on startup and when returning from background. 

If the result is NOT_DETERMINED then you can assume that the system popup will be shown when you call AppTrackingTransparency.RequestTrackingAuthorization.

**Comment by manelizzard** [comment]
Thank you @andymads. Exactly, when we obtain `NOT_DETERMINED` as the first result, we assume the popup will be shown upon `AppTrackingTransparency.RequestTrackingAuthorization`.

There is nothing we can query to determine if the popup was shown or not.

Hope this helped you @SimonImpact

**Comment by SimonImpact** [comment]
Thank you @andymads and @manelizzard ! That answered my question.
