### ISSUE TITLE
Does not work on iOS 14.3 and 14.4

### ISSUE THREAD

**Issue by KWarp** [Balaso-Software/app-tracking-transparency-for-unity#16]
I bought this product and followed the instructions. On my iPhone XS running iOS 14.2, the Permissions popup appears correctly. On my iPhone 12 running iOS 14.4, it does not appear. It has been rejected repeatedly from the App Store over this technicality. Please help.

More information can be found at this ticket: https://developer.apple.com/forums/thread/669490

**Comment by manelizzard** [comment]
Hello @KWarp. It has been proved XCode 12.3 does have some bugs on the ATT library. Are you using that version? If so, would you please update to latest XCode version?

This issue might be related: https://github.com/Balaso-Software/app-tracking-transparency-for-unity/issues/18

Thanks

**Comment by KWarp** [comment]
Unfortunately, I am seeing this issue on XCode 12.4

**Comment by KWarp** [comment]
I deleted my XCode 12.4 project and regenerated it with Unity. Now App Tracking Transparency works! The native framework must have needed to be rebuilt.

**Comment by manelizzard** [comment]
Thanks for checking @KWarp!
