### ISSUE TITLE
Is there a way to 'Cancel Auth' so we can test flow again?

### ISSUE THREAD

**Issue by AnthonyDemanueleFSG** [Balaso-Software/app-tracking-transparency-for-unity#18]
Hello! We just purchased your plugin and was wondering how we can repeat a few tests.  Is there a way to cancel the 'Auth' so we get to request permission again?

Thank you.

**Comment by andymads** [comment]
Delete the app and reinstall.

**Comment by AnthonyDemanueleFSG** [comment]
I tried this but it stays authorized.

**Comment by andymads** [comment]
Works for me every time.

**Comment by AnthonyDemanueleFSG** [comment]
I'm testing on iPhone X on V14.4. What are you testing it on?

**Comment by andymads** [comment]
I've used an iPad with 14.0 beta and 14.2 and 14.5 beta, and an iPhone SE with 14.2.

**Comment by andymads** [comment]
Are you sure you haven't disabled tracking in Settings?

**Comment by AnthonyDemanueleFSG** [comment]
Where could that be in settings? But I don't think that's the case because I'm getting 'Authorized' and I can see the IDFA too.

**Comment by andymads** [comment]
It's under Privacy/Tracking but it's not relevant if you're already getting Authorized.

On 14.4 you will get the IDFA as it's not turned off until 14.5.

**Comment by AnthonyDemanueleFSG** [comment]
I see my game under that menu.  If I delete the game, the entry goes away but when I install it again, I get 'Authorized' right away.

I never get the prompt asking me to allow tracking or not.

**Comment by andymads** [comment]
Can't say I've witnessed that behaviour - although I haven't tried with iOS 14.4.

**Comment by AnthonyDemanueleFSG** [comment]
@andymads are you the developer?

**Comment by andymads** [comment]
Nope. I'm just a user of this package.

**Comment by manelizzard** [comment]
After some investigation and discussion, the issue was reproducible on XCode 12.3. Updating to XCode 12.4 does fix the issue.

Thanks @AnthonyDemanueleFSG for your feedback
