### ISSUE TITLE
Unity Cloud Build failing

### ISSUE THREAD

**Issue by jgauciniski** [Balaso-Software/app-tracking-transparency-for-unity#19]
Hello,

My Unity Cloud build is failing after the package integration.
UCB configuration:
 - Unity 2019.2.21f1
 - Xcode Latest (Xcode 11.4.1)
 
I have the following issue:
"ld: framework not found AppTrackingTransparency"
 
It works when I build locally since my XCode is 12.4, but I can only use XCode 12 on Unity Cloud Build if I upgrade my Unity to 2019.3 (which will break lots of my third party plugins)

Is there an alternative solution for this issue? How can I make the AppTrackingTransparency framework work on XCode 11.4?

Thanks in advance

**Comment by manelizzard** [comment]
Hello @jgauciniski.

Unfortunately I don't think there is a way of building AppTrackingTransparency compatible builds with XCode 11. It may worth giving a try to updating to 2019.3 or even better: 2019.4, which is the LTS version.

Best of luck

**Comment by jgauciniski** [comment]
OK

Thank you very much!
--
Juliano Gauciniski
ITIL, Prince2™ Practitioner, PMP, MSc.

**Comment by jgauciniski** [comment]
Hello, 

It’s me again. I upgraded my Unity and now I am able to build, but Xcode is showing me this error:




My guess is something on the post processing script?
--
Juliano Gauciniski
ITIL, Prince2™ Practitioner, PMP, MSc.
Mobile: +1(604) 313-0656
