### ISSUE TITLE
TaskScheduler' exists in both 'Unity.Tasks

### ISSUE THREAD

**Issue by combatsheep** [Balaso-Software/app-tracking-transparency-for-unity#21]
Hello.
When I imported App Tracking Transparency for Unity into my project, I got the following error and couldn't proceed.
Is there a way to solve it?
Thank you.
---
Assets/Balaso Software/Runtime/AppTrackingTransparency.cs(75,24): error CS0433: The type 'TaskScheduler' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
---

**Comment by manelizzard** [comment]
Hello @combatsheep. Do you have Scripting Runtime Version to .NET 4.x Equivalent in Unity?

<img width="636" alt="net4" src="https://user-images.githubusercontent.com/895589/116115364-993d6e80-a6ba-11eb-9a9f-412bb068f9d1.png">

Have you tried any of the solutions shared here: https://forum.unity.com/threads/type-task-exists-in-both-unity-tasks-and-mscorelib.855385/?

**Comment by combatsheep** [comment]
Hello, @manelizzard.

>Do you have Scripting Runtime Version to .NET 4.x Equivalent in Unity?
No, it's .NET 4.x.

I'm sorry I forgot to fill in the environment.
Unity 2019.4.18f1

Is there any other place to check the settings?
Thank you.

![Scene_Game_-_PlayClock_Unity_-_iOS_-_Unity_2019_4_18f1_Personal__PREVIEW_PACKAGES_IN_USE___Personal___Metal_](https://user-images.githubusercontent.com/5697196/116162508-e9efae80-a730-11eb-8c2b-38c9a95a8982.jpg)

**Comment by manelizzard** [comment]
Hello @combatsheep, that looks fine.

What about the solutions shared in the link I pasted above?

**Comment by combatsheep** [comment]
Hello, @manelizzard.

Thank you! !!
In the forum you taught me, It was written "go to: youProjectFolder \ Assets \ Parse \ Plugins"
remove all files outside of the dotNet45 Folder ", so I tried it and it was solved!
It was helpful!

**Comment by manelizzard** [comment]
Glad to hear that @combatsheep 💪
