### ISSUE TITLE
Doubts in App Tracking Transparency Unity Asset Store

### ISSUE THREAD

**Issue by flowwaterfountain** [Balaso-Software/app-tracking-transparency-for-unity#22]
Hello, 
I have updated to version 2.3 today. When I test it in the simulator, the pop up language is in chinesse when the language in the Simulator is English. How can I change this? Do I have to parametizer it in some place?

**Comment by manelizzard** [comment]
Hello @flowwaterfountain,

Have you customized the pop-up message for Chinese or English? Can you share the Settings.asset file so we can take a look?

Another check: on the generated XCode project, under "Balaso Resources", which languages do you see?

Thank you

**Comment by manelizzard** [comment]
Hello @flowwaterfountain,

We have identified the issue and a fix is on its way (v2.3.1). Until it is live in Unity Asset Store (~2 working days), please set the `Use Localization Values` to `false`. It will default to English.

<img width="891" alt="use_localization_values" src="https://user-images.githubusercontent.com/895589/116365040-24c31680-a805-11eb-8025-018bffe6392e.png">

Thanks for your feedback and sorry for the inconveniences

**Comment by flowwaterfountain** [comment]
I send the settings.asset. I have customized the language to English. (see
attachments)

Under Balaso Resources I can see: ca. de, en, es, fr, ja, ko, zh (.lproj
all of them).

Regards,

**Comment by kymoto11** [comment]
Hi! Is this also related to Xcode not being able to find the ko, ja, zh, and fr .proj files?

Thanks.

**Comment by manelizzard** [comment]
Hello @mochibits.

No, it was identified an issue the en.lproj localization strings was filled with Chinese Traditional localization, instead of English.

Are you having any other issue?

**Comment by kymoto11** [comment]
Xcode had a build failure because it was specifically missing the ko, ja, zh, and fr .proj files. Apologizes for adding it to this thread. I can start a new Issue if needed. I've responded in the Unity thread too. I also had the same Crashing issue another Unity thread commenter experienced.

**Comment by manelizzard** [comment]
@mochibits what if you try to set `Use Localization Values` to false? Still fails to build?

What XCode and Unity versions are you using?

**Comment by manelizzard** [comment]
Version 2.3.1 has been reviewed and approved by Unity. It is now live in the Asset Store. I encourage you to update it.

Please, do not hesitate to reopen this ticket or file a new bug if you find something else.

Best

**Comment by kymoto11** [comment]
Yes. I've set Use Localization Values -> False, and rebuilt with the previous version, and it compiled and works.

I have not tried the new version. Thanks for the update! Great asset.
