### ISSUE TITLE
issue with localization

### ISSUE THREAD

**Issue by agrobost** [Balaso-Software/app-tracking-transparency-for-unity#23]
I don't have a recent enough iPhone to test this new popup, so I updated the plugin and sent directly for submission to apple but the application was rejected because:
```
We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect:

- Your app's modal alerts are written in Chinese while the app is set to the English localization. To help users understand why your app is requesting access to a specific feature, your app's modal alerts should be in the same language as your app's current localization.
```
![image](https://user-images.githubusercontent.com/14184466/116506900-84c9c380-a8be-11eb-8aac-f52dbd85066e.png)
I did not touch the default settings and I used the AppTrackingTransparencyExample.cs script

**Comment by manelizzard** [comment]
Hello @agrobost,

Indeed. Unfortunately we identified an issue and a fix it's on its way. Hopefully it is live today. See here: https://github.com/Balaso-Software/app-tracking-transparency-for-unity/issues/22#issuecomment-828226958

Sorry for any inconvenience

**Comment by manelizzard** [comment]
Hello again @agrobost,

Version 2.3.1 has been reviewed and approved by Unity. It is now live in the Asset Store. I encourage you to update it.

Please, do not hesitate to reopen this ticket or file a new bug if you find something else.

Best
