### ISSUE TITLE
The type 'TaskScheduler' exists in both 'Unity.Tasks...

### ISSUE THREAD

**Issue by Vasheer26** [Balaso-Software/app-tracking-transparency-for-unity#25]
Hi 
I just imported the plugin into my project and got this error.
Assets/Balaso Software/Runtime/AppTrackingTransparency.cs(73,47): error CS0433: The type 'TaskScheduler' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

I am using Unity 2019.4.18f.

The code it is referring to this:
       private static System.Threading.Tasks.TaskScheduler currentSynchronizationContext;
       
Any suggestions?

Thanks.

**Comment by manelizzard** [comment]
Hello @Vasheer26.

Please refer to https://github.com/Balaso-Software/app-tracking-transparency-for-unity/issues/21 to find the solution.

Thanks!
