### ISSUE TITLE
How to use it with different Ads network, Like Unity Ads & Admob

### ISSUE THREAD

**Issue by AsifNaeem1** [Balaso-Software/app-tracking-transparency-for-unity#26]
Hi, Thank you for this plugin, I recently purchase that plugin to comply with IOS 14+ guidelines.

I have few confusion while using your plugin. Please guide me.

I am using Unity 3D ads & Admob ads. How to use it with both SDK's? 

As you know Google Admob provide its own workaround to show the App app tracking transparency, and Unity has its own.
I am confused between both Ads provider.
Do I need to follow Google Admob & Unity 3D workout or your plugin is enough?

**Comment by manelizzard** [comment]
Hello @AsifNaeem1,

This plugin allows you to show ATT popup. AdMob and Unity solutions will also do the same, so it is enough if you use any of those 3 solutions.

Best
