### ISSUE TITLE
 iOS Build faild 

### ISSUE THREAD

**Issue by gmi19941998** [Balaso-Software/app-tracking-transparency-for-unity#28]
Hi, we have some problem with iOS build. We use Unity 2019.4.21f1.Field "Use Localization Value" is enabled(If disable, build assemble normal). Also we use I2 Localization. Can u help resolve this issue? 
![Screenshot_318](https://user-images.githubusercontent.com/54501732/117543760-d4c72980-b026-11eb-8102-1fe673cde5ae.png)

**Comment by manelizzard** [comment]
Hello @gmi19941998. Are those folders available in your project? Are you having any build error while exporting the XCode project from Unity?

- .../ru.lproj
- .../zh.lproj
- etc...

**Comment by gmi19941998** [comment]
They are not available in the project. Only empty  /en.lproj
