### ISSUE TITLE
Upload iOS with warning by.lproj

### ISSUE THREAD

**Issue by phamhphuc** [Balaso-Software/app-tracking-transparency-for-unity#29]
Dear,

Today I upload with warning by.lproj

"WARNING ITMS-90176: "Unrecognized Locale - The locale names used in localization directories at ( ".app/by.lproj" ) are invalid. iTunes supports BCP47 but not the UN M.49 specification. Refer to the Language and Locale Designations guide at https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html for more information on naming your language-specific directories."

Can I solve this issue just delete by.lproj in Xcode?

Thanks,
Phuc

**Comment by manelizzard** [comment]
Hello @phamhphuc,

Sure, you might delete that folder on the XCode project and it whould work.

Thanks

**Comment by phamhphuc** [comment]
That's cool. Thank you very much
