### ISSUE TITLE
Getting error during build in xcode

### ISSUE THREAD

**Issue by vishnudevasi** [Balaso-Software/app-tracking-transparency-for-unity#3]
hi 
i used your app tracking transparency asset for unity and during buid in xcode i get error so
please help me to solve this error showinig in below image
Detail:
Unity v2020.1.0f1
Xcode v11.6
target iOS11
<img width="1330" alt="Screenshot 2020-08-18 at 11 02 24 PM" src="https://user-images.githubusercontent.com/33121223/90548554-bf655300-e1aa-11ea-85f9-215f2f1cf01e.png">

**Comment by manelizzard** [comment]
Hello. This plugin can only be built on XCode 12. Please try with XCode 12 Beta 4.
