### ISSUE TITLE
 AppTrackingTransparency.RequestTrackingAuthorization() keep getting status "Denied"

### ISSUE THREAD

**Issue by affinixy** [Balaso-Software/app-tracking-transparency-for-unity#30]
Hi, I managed to build for testing in Testflight, but I keep receiving "Denied" as the log.

This is my Manager script, and I have a button to trigger the native dialog, but when i press the button, I keep getting the status "Denied". Is there anything I am missing?

This is my C# script
https://www.dropbox.com/s/nc9qxmx8pzrscg1/iOSAppTrackingTransparencyManager.cs?dl=0

**Comment by affinixy** [comment]
Updates, I tried building the game with your Sample scene to Testflight, and there is no native dialog as well. Is the script suppose to work in launch build in App Store only?

**Comment by jay-neb** [comment]
Hi @affinixy, I'm having the same issue. Did you solve it?
