### ISSUE TITLE
Not Showing Pop up

### ISSUE THREAD

**Issue by vishnudevasi** [Balaso-Software/app-tracking-transparency-for-unity#4]
hi
 Its build Successfully in Xcode 12 but I didn't see any Pop-up in my XR device and in Xcode log its showing Authorization status: Authorized and also obtaining IDFA but didn't see any Pop-up so why this happen?

Thanks

**Comment by manelizzard** [comment]
Hello @vishnudevasi,

Which iOS version is running on your XR device? Authorization popup will only show on iOS 14+ devices

**Comment by vishnudevasi** [comment]
oh ok got it
my iOS version is 13.3.1

**Comment by manelizzard** [comment]
That's perfectly fine. For iOS 13 and lower devices, the [ASIdentifierManager](https://developer.apple.com/documentation/adsupport/asidentifiermanager) is used, so popup won't show but you'll get proper authorization status and IDFA.

When your device updates to iOS 14, then you'll see the popup when requesting the authorization.
