### ISSUE TITLE
Error right after importing

### ISSUE THREAD

**Issue by VaasInsanity** [Balaso-Software/app-tracking-transparency-for-unity#5]
Got many errors right after importing the plugin
`Assets/Balaso Software/Runtime/AppTrackingTransparency.cs(35,24): error CS1644: Feature `interpolated strings' cannot be used because it is not part of the C# 4.0 language specification`
`Assets/Balaso Software/Runtime/AppTrackingTransparency.cs(118,24): error CS1644: Feature `interpolated strings' cannot be used because it is not part of the C# 4.0 language specification`
`Assets/Balaso Software/Runtime/AppTrackingTransparency.cs(119,39): error CS1644: Feature `null propagating operator' cannot be used because it is not part of the C# 4.0 language specification
`
`Assets/Balaso Software/Runtime/AppTrackingTransparency.cs(142,24): error CS1644: Feature `interpolated strings' cannot be used because it is not part of the C# 4.0 language specification
`

**Comment by manelizzard** [comment]
Hello,

You need to use .NET 4.x. Follow this steps: https://stackoverflow.com/a/51851721
