### ISSUE TITLE
No access to trackingAuthorizationStatus property

### ISSUE THREAD

**Issue by whoover** [Balaso-Software/app-tracking-transparency-for-unity#6]
Is it possible add property to your lib?

**Comment by manelizzard** [comment]
Hello @whoover,

Thanks for your suggestion. Will add it to the next release.

**Comment by jaceks454** [comment]
Hi @manelizzard 
Any timeframe when new version can be available?

**Comment by manelizzard** [comment]
Potentially by the end of this week, beginning of next.

**Comment by manelizzard** [comment]
Available on version **2.0**, already live:
- [Website](https://balaso-software.github.io/app-tracking-transparency-for-unity/)
- [Unity Asset Store](https://assetstore.unity.com/packages/tools/integration/app-tracking-transparency-for-unity-ios-14-idfa-174256)
