### ISSUE TITLE
Crash on ios 13

### ISSUE THREAD

**Issue by Polarhigh** [Balaso-Software/app-tracking-transparency-for-unity#7]
Hi! I have encountered a crash on ios version lower than 14

log
> Error loading /var/containers/Bundle/Application/99E72082-3A2D-412F-A90F-0140AE0F7CD6/myapp.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/99E72082-3A2D-412F-A90F-0140AE0F7CD6/myapp.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): dependent dylib '/System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency' not found for '/private/var/containers/Bundle/Application/99E72082-3A2D-412F-A90F-0140AE0F7CD6/myapp.app/Frameworks/UnityFramework.framework/UnityFramework'

In my project i fixed it in AppTrackingTransparencyPostProcessor.OnPostprocessBuild:
`project.AddFrameworkToProject(targetId, "AppTrackingTransparency.framework", false);`
replaced by
`project.AddFrameworkToProject(targetId, "AppTrackingTransparency.framework", true);`

Everything seems to work fine, but is it enough to 100% fix the issue?

**Comment by manelizzard** [comment]
Hello! Yes, that should be enough. On iOS 13, that framework is not available. Will fix it in the plugin. Thanks! :)

**Comment by manelizzard** [comment]
Should be fixed on version 2.1
