### ISSUE TITLE
App Tracking Transparency dialog box not showing

### ISSUE THREAD

**Issue by jk296** [Balaso-Software/app-tracking-transparency-for-unity#8]
Hi,
I purchased and installed the asset "App Tracking Transparency for Unity - iOS 14 IDFA" v2.1 on Unity 2018.4.27f1. The building in Unity was successful, and the installation (Xcode 12.0) on my iPhone 6 plus (iOS 12.4.8) was also successful. I could run my app on my phone. However the App Tracking Transparency dialog box doesn't show up at all. Can you help, please?

**Comment by manelizzard** [comment]
@jk296 App Tracking Transparency dialog box only shows on iOS 14+
